set_undoable_attribute [get_cells -all ipad_ctrl_si] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi4] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi3] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi2] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi1] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi0] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_load_n] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_cpu_bgn] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_ctrl_bgn] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_ctrl_mode1] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_ctrl_mode0] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_rst_n] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_clk] is_fixed {1}
set_undoable_attribute [get_cells -all opad_spi_so] is_fixed {1}
set_undoable_attribute [get_cells -all opad_lat] is_fixed {1}
set_undoable_attribute [get_cells -all opad_sclk2] is_fixed {1}
set_undoable_attribute [get_cells -all opad_sclk1] is_fixed {1}
set_undoable_attribute [get_cells -all opad_nxt1] is_fixed {1}
set_undoable_attribute [get_cells -all opad_nxt0] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_cpu_wait] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_app_done] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_test_mux0] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_test_mux1] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_test_mux2] is_fixed {1}
set_undoable_attribute [get_cells -all opad_app_start] is_fixed {1}
set_undoable_attribute [get_cells -all opad_ctrl_so] is_fixed {1}
set_undoable_attribute [get_cells -all opad_ctrl_rdy] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi9] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi8] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi7] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi6] is_fixed {1}
set_undoable_attribute [get_cells -all ipad_adc_pi5] is_fixed {1}
